# Form implementation generated from reading ui file 'bienvenidaSistema.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget{\n"
"background-color:rgb(75,145,210);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icono_Proyecto/image 34.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Icono_Proyecto/Facturitec_logo_transparent 1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_6.setStyleSheet("QPushButton{\n"
"padding: 20px;\n"
"border-radius: 20px;\n"
"background-color: none;\n"
"font-size: 20px;\n"
"font-family: arial;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(50)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_IniciarApp = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_IniciarApp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_IniciarApp.setStyleSheet("QPushButton{\n"
"background-color: rgb(62,46,158);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72,56,168);\n"
"border:1px solid black;\n"
"}\n"
"\n"
"")
        self.pushButton_IniciarApp.setObjectName("pushButton_IniciarApp")
        self.verticalLayout_4.addWidget(self.pushButton_IniciarApp)
        self.pushButton_SalirBienvenida = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_SalirBienvenida.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pushButton_SalirBienvenida.setStyleSheet("QPushButton{\n"
"background-color: rgb(255,255,255);\n"
"color:black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(240,240,240);\n"
"border:1px solid black;\n"
"}")
        self.pushButton_SalirBienvenida.setObjectName("pushButton_SalirBienvenida")
        self.verticalLayout_4.addWidget(self.pushButton_SalirBienvenida)
        self.horizontalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setStyleSheet("QLabel{\n"
"font-family:arial;\n"
"font-size: 15px;\n"
"color:white;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(0, 80)
        self.verticalLayout_3.setStretch(1, 20)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.setStretch(0, 20)
        self.verticalLayout_2.setStretch(1, 80)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_IniciarApp.setText(_translate("MainWindow", "INICIAR"))
        self.pushButton_SalirBienvenida.setText(_translate("MainWindow", "SALIR"))
        self.label_2.setText(_translate("MainWindow", "Email: dir_acapulco@tecnm.mx   (744) 309-2200"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
