# Form implementation generated from reading ui file 'interfazMenuPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 858)
        MainWindow.setMinimumSize(QtCore.QSize(50, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("*{\n"
"border:none;\n"
"background-color:trasparent;\n"
"background:none;\n"
"padding: 0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"#centralwidget{\n"
"background-color:rgb(255,255,255);\n"
"}\n"
"#subcontenedorBarraLateral{\n"
"background-color:rgb(214,210,218);\n"
"padding: 2px 5px;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contenedorBarraLateral = QtWidgets.QWidget(parent=self.centralwidget)
        self.contenedorBarraLateral.setStyleSheet("")
        self.contenedorBarraLateral.setObjectName("contenedorBarraLateral")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contenedorBarraLateral)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subcontenedorBarraLateral = QtWidgets.QWidget(parent=self.contenedorBarraLateral)
        self.subcontenedorBarraLateral.setStyleSheet("QPushButton{\n"
"font-family: Arial;        \n"
"font-size: 14px;          \n"
"color: black; \n"
"}\n"
"QLabel{\n"
"font-family: Arial;        \n"
"font-size: 14px;          \n"
"color: white; \n"
"}")
        self.subcontenedorBarraLateral.setObjectName("subcontenedorBarraLateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subcontenedorBarraLateral)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superiorBarraLateral = QtWidgets.QFrame(parent=self.subcontenedorBarraLateral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_superiorBarraLateral.sizePolicy().hasHeightForWidth())
        self.frame_superiorBarraLateral.setSizePolicy(sizePolicy)
        self.frame_superiorBarraLateral.setStyleSheet("QFrame{\n"
"background-color: rgb(21,10,89);\n"
"border-radius:5px\n"
"}\n"
"")
        self.frame_superiorBarraLateral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superiorBarraLateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superiorBarraLateral.setObjectName("frame_superiorBarraLateral")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_superiorBarraLateral)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_Aplicacion = QtWidgets.QFrame(parent=self.frame_superiorBarraLateral)
        self.frame_Aplicacion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Aplicacion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Aplicacion.setObjectName("frame_Aplicacion")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_Aplicacion)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_iconoApp = QtWidgets.QLabel(parent=self.frame_Aplicacion)
        self.label_iconoApp.setMaximumSize(QtCore.QSize(125, 110))
        self.label_iconoApp.setText("")
        self.label_iconoApp.setPixmap(QtGui.QPixmap("Icono_Proyecto/LOGOFACTURITEC 1.png"))
        self.label_iconoApp.setScaledContents(True)
        self.label_iconoApp.setObjectName("label_iconoApp")
        self.horizontalLayout_3.addWidget(self.label_iconoApp)
        self.label_nombreAplicacion = QtWidgets.QLabel(parent=self.frame_Aplicacion)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_nombreAplicacion.setFont(font)
        self.label_nombreAplicacion.setObjectName("label_nombreAplicacion")
        self.horizontalLayout_3.addWidget(self.label_nombreAplicacion)
        self.verticalLayout_5.addWidget(self.frame_Aplicacion)
        self.frame_Emisor = QtWidgets.QFrame(parent=self.frame_superiorBarraLateral)
        self.frame_Emisor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Emisor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Emisor.setObjectName("frame_Emisor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Emisor)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_Emisor)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_iconoUsuario = QtWidgets.QLabel(parent=self.frame_7)
        self.label_iconoUsuario.setText("")
        self.label_iconoUsuario.setPixmap(QtGui.QPixmap("Icono_Proyecto/Icono_Persona.png"))
        self.label_iconoUsuario.setObjectName("label_iconoUsuario")
        self.horizontalLayout_30.addWidget(self.label_iconoUsuario)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_Emisor)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.LabelUsuario = QtWidgets.QLabel(parent=self.frame_10)
        self.LabelUsuario.setObjectName("LabelUsuario")
        self.horizontalLayout_31.addWidget(self.LabelUsuario)
        self.label_NombreEmisor = QtWidgets.QLabel(parent=self.frame_10)
        self.label_NombreEmisor.setText("")
        self.label_NombreEmisor.setObjectName("label_NombreEmisor")
        self.horizontalLayout_31.addWidget(self.label_NombreEmisor)
        self.verticalLayout_21.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.LabelCargo = QtWidgets.QLabel(parent=self.frame_9)
        self.LabelCargo.setObjectName("LabelCargo")
        self.horizontalLayout_32.addWidget(self.LabelCargo)
        self.label_CargoEmisor = QtWidgets.QLabel(parent=self.frame_9)
        self.label_CargoEmisor.setText("")
        self.label_CargoEmisor.setObjectName("label_CargoEmisor")
        self.horizontalLayout_32.addWidget(self.label_CargoEmisor)
        self.verticalLayout_21.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.verticalLayout_5.addWidget(self.frame_Emisor)
        self.verticalLayout_2.addWidget(self.frame_superiorBarraLateral)
        self.frame_opcionesPrincipales = QtWidgets.QFrame(parent=self.subcontenedorBarraLateral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_opcionesPrincipales.sizePolicy().hasHeightForWidth())
        self.frame_opcionesPrincipales.setSizePolicy(sizePolicy)
        self.frame_opcionesPrincipales.setStyleSheet("\n"
"QPushButton{\n"
"background-color: transparent;\n"
"text-align:left;\n"
"\n"
"padding: 2px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(21,10,89);\n"
"color: white;\n"
"}\n"
"\n"
"")
        self.frame_opcionesPrincipales.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_opcionesPrincipales.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_opcionesPrincipales.setObjectName("frame_opcionesPrincipales")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_opcionesPrincipales)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_3.setSpacing(40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_Alumno = QtWidgets.QPushButton(parent=self.frame_opcionesPrincipales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Alumno.sizePolicy().hasHeightForWidth())
        self.pushButton_Alumno.setSizePolicy(sizePolicy)
        self.pushButton_Alumno.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icono_Proyecto/Seccion_Hijo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Alumno.setIcon(icon)
        self.pushButton_Alumno.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_Alumno.setObjectName("pushButton_Alumno")
        self.verticalLayout_3.addWidget(self.pushButton_Alumno)
        self.pushButton_Padre = QtWidgets.QPushButton(parent=self.frame_opcionesPrincipales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Padre.sizePolicy().hasHeightForWidth())
        self.pushButton_Padre.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icono_Proyecto/Seccion_Padre.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Padre.setIcon(icon1)
        self.pushButton_Padre.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_Padre.setObjectName("pushButton_Padre")
        self.verticalLayout_3.addWidget(self.pushButton_Padre)
        self.pushButton_NuevaFactura = QtWidgets.QPushButton(parent=self.frame_opcionesPrincipales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NuevaFactura.sizePolicy().hasHeightForWidth())
        self.pushButton_NuevaFactura.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icono_Proyecto/Seccion_Factura.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_NuevaFactura.setIcon(icon2)
        self.pushButton_NuevaFactura.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_NuevaFactura.setObjectName("pushButton_NuevaFactura")
        self.verticalLayout_3.addWidget(self.pushButton_NuevaFactura)
        self.pushButton_Informes = QtWidgets.QPushButton(parent=self.frame_opcionesPrincipales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Informes.sizePolicy().hasHeightForWidth())
        self.pushButton_Informes.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icono_Proyecto/Seccion_Estadistica.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Informes.setIcon(icon3)
        self.pushButton_Informes.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_Informes.setObjectName("pushButton_Informes")
        self.verticalLayout_3.addWidget(self.pushButton_Informes)
        self.pushButton_Bitacora = QtWidgets.QPushButton(parent=self.frame_opcionesPrincipales)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Bitacora.sizePolicy().hasHeightForWidth())
        self.pushButton_Bitacora.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icono_Proyecto/image 33.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Bitacora.setIcon(icon4)
        self.pushButton_Bitacora.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_Bitacora.setObjectName("pushButton_Bitacora")
        self.verticalLayout_3.addWidget(self.pushButton_Bitacora)
        self.verticalLayout_2.addWidget(self.frame_opcionesPrincipales)
        self.frame_inferiorBarraLateral = QtWidgets.QFrame(parent=self.subcontenedorBarraLateral)
        self.frame_inferiorBarraLateral.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"padding: 3px;\n"
"}\n"
"")
        self.frame_inferiorBarraLateral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferiorBarraLateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferiorBarraLateral.setObjectName("frame_inferiorBarraLateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_inferiorBarraLateral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_Respaldo = QtWidgets.QPushButton(parent=self.frame_inferiorBarraLateral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Respaldo.sizePolicy().hasHeightForWidth())
        self.pushButton_Respaldo.setSizePolicy(sizePolicy)
        self.pushButton_Respaldo.setStyleSheet("QPushButton{\n"
"background-color:rgb(190,190,190);\n"
"}\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(80,150,210);\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icono_Proyecto/Crear_respaldo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Respaldo.setIcon(icon5)
        self.pushButton_Respaldo.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_Respaldo.setObjectName("pushButton_Respaldo")
        self.verticalLayout_4.addWidget(self.pushButton_Respaldo)
        self.pushButton_Cerrarsesion = QtWidgets.QPushButton(parent=self.frame_inferiorBarraLateral)
        self.pushButton_Cerrarsesion.setStyleSheet("QPushButton{\n"
"background-color:rgb(21,10,89);\n"
"color: white;\n"
"}\n"
"QPushButton:hover{\n"
"border: 1px solid white;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icono_Proyecto/cerrar sesion.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Cerrarsesion.setIcon(icon6)
        self.pushButton_Cerrarsesion.setIconSize(QtCore.QSize(20, 34))
        self.pushButton_Cerrarsesion.setObjectName("pushButton_Cerrarsesion")
        self.verticalLayout_4.addWidget(self.pushButton_Cerrarsesion)
        self.verticalLayout_2.addWidget(self.frame_inferiorBarraLateral)
        self.verticalLayout.addWidget(self.subcontenedorBarraLateral, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.contenedorBarraLateral)
        self.contenedorPrincipal = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contenedorPrincipal.sizePolicy().hasHeightForWidth())
        self.contenedorPrincipal.setSizePolicy(sizePolicy)
        self.contenedorPrincipal.setObjectName("contenedorPrincipal")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contenedorPrincipal)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_Superior = QtWidgets.QFrame(parent=self.contenedorPrincipal)
        self.frame_Superior.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Superior.sizePolicy().hasHeightForWidth())
        self.frame_Superior.setSizePolicy(sizePolicy)
        self.frame_Superior.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_Superior.setStyleSheet("")
        self.frame_Superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Superior.setObjectName("frame_Superior")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_Superior)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_logotecnm = QtWidgets.QFrame(parent=self.frame_Superior)
        self.frame_logotecnm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_logotecnm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_logotecnm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_logotecnm.setObjectName("frame_logotecnm")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_logotecnm)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_imagenLogotecnm = QtWidgets.QLabel(parent=self.frame_logotecnm)
        self.label_imagenLogotecnm.setText("")
        self.label_imagenLogotecnm.setPixmap(QtGui.QPixmap("Icono_Proyecto/logo-tecnm.png"))
        self.label_imagenLogotecnm.setScaledContents(True)
        self.label_imagenLogotecnm.setObjectName("label_imagenLogotecnm")
        self.horizontalLayout_5.addWidget(self.label_imagenLogotecnm)
        self.horizontalLayout_4.addWidget(self.frame_logotecnm)
        spacerItem = QtWidgets.QSpacerItem(586, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frame_logoITA = QtWidgets.QFrame(parent=self.frame_Superior)
        self.frame_logoITA.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_logoITA.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_logoITA.setObjectName("frame_logoITA")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_logoITA)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_imagenLogoITA = QtWidgets.QLabel(parent=self.frame_logoITA)
        self.label_imagenLogoITA.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_imagenLogoITA.setText("")
        self.label_imagenLogoITA.setPixmap(QtGui.QPixmap("Icono_Proyecto/logo-ita.png"))
        self.label_imagenLogoITA.setScaledContents(True)
        self.label_imagenLogoITA.setObjectName("label_imagenLogoITA")
        self.horizontalLayout_6.addWidget(self.label_imagenLogoITA)
        self.horizontalLayout_4.addWidget(self.frame_logoITA)
        self.verticalLayout_6.addWidget(self.frame_Superior)
        self.frame_Principal = QtWidgets.QFrame(parent=self.contenedorPrincipal)
        self.frame_Principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Principal.setObjectName("frame_Principal")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_Principal)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_Principal)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Principal = QtWidgets.QWidget()
        self.page_Principal.setObjectName("page_Principal")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_Principal)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_Bienvenida = QtWidgets.QLabel(parent=self.page_Principal)
        self.label_Bienvenida.setStyleSheet("QLabel{\n"
"font-size: 15px;\n"
"font-family: arial;\n"
"color:rgb(75,145,210)\n"
"}")
        self.label_Bienvenida.setObjectName("label_Bienvenida")
        self.verticalLayout_8.addWidget(self.label_Bienvenida, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget.addWidget(self.page_Principal)
        self.page_Alumno = QtWidgets.QWidget()
        self.page_Alumno.setStyleSheet("QPushButton{\n"
"font-size:16;\n"
"font-family:Arial;\n"
"color:rgb(0,0,0);\n"
"}\n"
"QLineEdit{\n"
"border-radius:5px;\n"
"background-color: rgb(217,217,217);\n"
"padding: 5px;\n"
"color: rgb(0,0,0);\n"
"\n"
"font-size: 16px;\n"
"font-family:Arial;\n"
"}\n"
"\n"
"QLabel{\n"
"color:rgb(0,0,0);\n"
"font-family:Arial;\n"
"font-size:16px;\n"
"}\n"
"QComboBox{\n"
"color:black;\n"
"background-color:rgb(217,217,217);\n"
"border-radius:10px;\n"
"padding:5px;\n"
"font-size:16px;\n"
"font-family:Arial;\n"
"}\n"
"")
        self.page_Alumno.setObjectName("page_Alumno")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_Alumno)
        self.verticalLayout_9.setContentsMargins(0, 9, 0, 9)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_SuperiorAlumno = QtWidgets.QFrame(parent=self.page_Alumno)
        self.frame_SuperiorAlumno.setMaximumSize(QtCore.QSize(1000, 40))
        self.frame_SuperiorAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SuperiorAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SuperiorAlumno.setObjectName("frame_SuperiorAlumno")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_SuperiorAlumno)
        self.horizontalLayout_9.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_LupaBuscarAlumno = QtWidgets.QPushButton(parent=self.frame_SuperiorAlumno)
        self.pushButton_LupaBuscarAlumno.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_LupaBuscarAlumno.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icono_Proyecto/Lupa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_LupaBuscarAlumno.setIcon(icon7)
        self.pushButton_LupaBuscarAlumno.setIconSize(QtCore.QSize(34, 34))
        self.pushButton_LupaBuscarAlumno.setObjectName("pushButton_LupaBuscarAlumno")
        self.horizontalLayout_9.addWidget(self.pushButton_LupaBuscarAlumno)
        self.comboBox_BuscarAlumno = QtWidgets.QComboBox(parent=self.frame_SuperiorAlumno)
        self.comboBox_BuscarAlumno.setMaximumSize(QtCore.QSize(800, 16777215))
        self.comboBox_BuscarAlumno.setStyleSheet("")
        self.comboBox_BuscarAlumno.setEditable(True)
        self.comboBox_BuscarAlumno.setObjectName("comboBox_BuscarAlumno")
        self.horizontalLayout_9.addWidget(self.comboBox_BuscarAlumno)
        self.verticalLayout_9.addWidget(self.frame_SuperiorAlumno, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_PrincipalAlumno = QtWidgets.QFrame(parent=self.page_Alumno)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_PrincipalAlumno.sizePolicy().hasHeightForWidth())
        self.frame_PrincipalAlumno.setSizePolicy(sizePolicy)
        self.frame_PrincipalAlumno.setMaximumSize(QtCore.QSize(1000, 600))
        self.frame_PrincipalAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_PrincipalAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_PrincipalAlumno.setObjectName("frame_PrincipalAlumno")
        self.formLayout = QtWidgets.QFormLayout(self.frame_PrincipalAlumno)
        self.formLayout.setContentsMargins(40, 9, -1, 0)
        self.formLayout.setObjectName("formLayout")
        self.frame_LabelAlumno = QtWidgets.QFrame(parent=self.frame_PrincipalAlumno)
        self.frame_LabelAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_LabelAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_LabelAlumno.setObjectName("frame_LabelAlumno")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_LabelAlumno)
        self.verticalLayout_10.setContentsMargins(25, 0, 10, 0)
        self.verticalLayout_10.setSpacing(25)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_NombreAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_NombreAlumno.setObjectName("label_NombreAlumno")
        self.verticalLayout_10.addWidget(self.label_NombreAlumno)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.label_ApellidosAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_ApellidosAlumno.setObjectName("label_ApellidosAlumno")
        self.verticalLayout_10.addWidget(self.label_ApellidosAlumno)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.label_CurpAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_CurpAlumno.setObjectName("label_CurpAlumno")
        self.verticalLayout_10.addWidget(self.label_CurpAlumno)
        self.label_ClaveTrabajoAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_ClaveTrabajoAlumno.setObjectName("label_ClaveTrabajoAlumno")
        self.verticalLayout_10.addWidget(self.label_ClaveTrabajoAlumno)
        self.label_NivelEducativoAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_NivelEducativoAlumno.setObjectName("label_NivelEducativoAlumno")
        self.verticalLayout_10.addWidget(self.label_NivelEducativoAlumno)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.label_RFCtutorAlumno = QtWidgets.QLabel(parent=self.frame_LabelAlumno)
        self.label_RFCtutorAlumno.setObjectName("label_RFCtutorAlumno")
        self.verticalLayout_10.addWidget(self.label_RFCtutorAlumno)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.frame_LabelAlumno)
        self.frame_LineEditAlumno = QtWidgets.QFrame(parent=self.frame_PrincipalAlumno)
        self.frame_LineEditAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_LineEditAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_LineEditAlumno.setObjectName("frame_LineEditAlumno")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_LineEditAlumno)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(25)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_NombreAlumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_NombreAlumno.setMaxLength(50)
        self.lineEdit_NombreAlumno.setObjectName("lineEdit_NombreAlumno")
        self.verticalLayout_11.addWidget(self.lineEdit_NombreAlumno)
        self.lineEdit_ApellidoMalumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_ApellidoMalumno.setObjectName("lineEdit_ApellidoMalumno")
        self.verticalLayout_11.addWidget(self.lineEdit_ApellidoMalumno)
        self.lineEdit_ApellidoPalumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_ApellidoPalumno.setMaxLength(50)
        self.lineEdit_ApellidoPalumno.setObjectName("lineEdit_ApellidoPalumno")
        self.verticalLayout_11.addWidget(self.lineEdit_ApellidoPalumno)
        self.lineEdit_Fecha_Nacimiento = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_Fecha_Nacimiento.setStyleSheet("QLineEdit{\n"
"font-size: 15px;\n"
"font-family: arial;\n"
"color:rgb(75,145,210)\n"
"}")
        self.lineEdit_Fecha_Nacimiento.setObjectName("lineEdit_Fecha_Nacimiento")
        self.verticalLayout_11.addWidget(self.lineEdit_Fecha_Nacimiento)
        self.lineEdit_CURPalumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_CURPalumno.setObjectName("lineEdit_CURPalumno")
        self.verticalLayout_11.addWidget(self.lineEdit_CURPalumno)
        self.lineEdit_ClaveTrabajoAlumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_ClaveTrabajoAlumno.setObjectName("lineEdit_ClaveTrabajoAlumno")
        self.verticalLayout_11.addWidget(self.lineEdit_ClaveTrabajoAlumno)
        self.comboBox_NivelEducativo = QtWidgets.QComboBox(parent=self.frame_LineEditAlumno)
        self.comboBox_NivelEducativo.setStyleSheet("QComboBox{\n"
"padding: 5px;\n"
"border-radius:5px;\n"
"background-color:rgb(217,217,217);\n"
"color:black;\n"
"font-size:16px;\n"
"font-family:arial;\n"
"}")
        self.comboBox_NivelEducativo.setEditable(False)
        self.comboBox_NivelEducativo.setObjectName("comboBox_NivelEducativo")
        self.verticalLayout_11.addWidget(self.comboBox_NivelEducativo)
        self.label_CantidadPago = QtWidgets.QLabel(parent=self.frame_LineEditAlumno)
        self.label_CantidadPago.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_CantidadPago.setStyleSheet("QLabel{\n"
"font-size: 20px;\n"
"font-family: arial;\n"
"color:black;\n"
"Font-weight:bold;\n"
"}")
        self.label_CantidadPago.setObjectName("label_CantidadPago")
        self.verticalLayout_11.addWidget(self.label_CantidadPago)
        self.lineEdit_RFCtutorAlumno = QtWidgets.QLineEdit(parent=self.frame_LineEditAlumno)
        self.lineEdit_RFCtutorAlumno.setObjectName("lineEdit_RFCtutorAlumno")
        self.verticalLayout_11.addWidget(self.lineEdit_RFCtutorAlumno)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_LineEditAlumno)
        self.verticalLayout_9.addWidget(self.frame_PrincipalAlumno)
        self.frame_17 = QtWidgets.QFrame(parent=self.page_Alumno)
        self.frame_17.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background-color: rgb(206,202,210);\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_37.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_37.setSpacing(6)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.PushBoton_Insertar_Alumno = QtWidgets.QPushButton(parent=self.frame_17)
        self.PushBoton_Insertar_Alumno.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(80,150,210);\n"
"}")
        self.PushBoton_Insertar_Alumno.setObjectName("PushBoton_Insertar_Alumno")
        self.horizontalLayout_37.addWidget(self.PushBoton_Insertar_Alumno)
        self.PushBoton_Modificar_Alumno = QtWidgets.QPushButton(parent=self.frame_17)
        self.PushBoton_Modificar_Alumno.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.PushBoton_Modificar_Alumno.setObjectName("PushBoton_Modificar_Alumno")
        self.horizontalLayout_37.addWidget(self.PushBoton_Modificar_Alumno)
        self.PushBoton_Eliminar_Alumno = QtWidgets.QPushButton(parent=self.frame_17)
        self.PushBoton_Eliminar_Alumno.setEnabled(True)
        self.PushBoton_Eliminar_Alumno.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(210,50,50);\n"
"color:White;\n"
"}")
        self.PushBoton_Eliminar_Alumno.setObjectName("PushBoton_Eliminar_Alumno")
        self.horizontalLayout_37.addWidget(self.PushBoton_Eliminar_Alumno)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.page_Alumno)
        self.page_Bitacora = QtWidgets.QWidget()
        self.page_Bitacora.setObjectName("page_Bitacora")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_Bitacora)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_Bitacora)
        self.frame_4.setStyleSheet("QLabel{\n"
"color:black;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setStyleSheet("QLabel{\n"
"font-size: 25px;\n"
"font-family: arial;\n"
"color:black;\n"
"Font-weight:bold;\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_29.addWidget(self.label_4)
        self.verticalLayout_20.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(parent=self.page_Bitacora)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame_5)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background-color:rgb(217,217,217);\n"
"color: black;\n"
"font-size: 16px;\n"
"font-family:arial;\n"
"Padding:3px;\n"
"}\n"
"QHeaderView::section{ \n"
"color: black; \n"
"font-weight: bold; \n"
"}")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_27.addWidget(self.tableWidget)
        self.verticalLayout_20.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.page_Bitacora)
        self.frame_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(206,202,210);\n"
"color:black;\n"
"padding: 10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_28.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_28.setSpacing(50)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(80,150,210);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icono_Proyecto/Icono_Vizualizar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_28.addWidget(self.pushButton_2)
        self.verticalLayout_20.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_20.setStretch(0, 20)
        self.verticalLayout_20.setStretch(1, 70)
        self.verticalLayout_20.setStretch(2, 10)
        self.stackedWidget.addWidget(self.page_Bitacora)
        self.page_Factura = QtWidgets.QWidget()
        self.page_Factura.setStyleSheet("*{\n"
"padding:0px;\n"
"margin:0;\n"
"border:none;\n"
"background-color:trasparent;\n"
"background:none;\n"
"}\n"
"QLabel{\n"
"color:black;\n"
"font-size:16px;\n"
"font-family:Arial;\n"
"}\n"
"QLineEdit{\n"
"color:black;\n"
"background-color:rgb(217,217,217);\n"
"border-radius:10px;\n"
"padding:5px;\n"
"font-size:16px;\n"
"font-family:Arial;\n"
"}\n"
"QComboBox{\n"
"color:black;\n"
"background-color:rgb(217,217,217);\n"
"border-radius:10px;\n"
"padding:5px;\n"
"font-size:16px;\n"
"font-family:Arial;\n"
"}")
        self.page_Factura.setObjectName("page_Factura")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_Factura)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_SeleccionarPadre = QtWidgets.QFrame(parent=self.page_Factura)
        self.frame_SeleccionarPadre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SeleccionarPadre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SeleccionarPadre.setObjectName("frame_SeleccionarPadre")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_SeleccionarPadre)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_SeleccionPadre = QtWidgets.QFrame(parent=self.frame_SeleccionarPadre)
        self.frame_SeleccionPadre.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_SeleccionPadre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SeleccionPadre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SeleccionPadre.setObjectName("frame_SeleccionPadre")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_SeleccionPadre)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_lupaSeleccionarPadre = QtWidgets.QPushButton(parent=self.frame_SeleccionPadre)
        self.pushButton_lupaSeleccionarPadre.setText("")
        self.pushButton_lupaSeleccionarPadre.setIcon(icon7)
        self.pushButton_lupaSeleccionarPadre.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_lupaSeleccionarPadre.setObjectName("pushButton_lupaSeleccionarPadre")
        self.horizontalLayout_14.addWidget(self.pushButton_lupaSeleccionarPadre)
        self.comboBox_SeleccionarPadre = QtWidgets.QComboBox(parent=self.frame_SeleccionPadre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SeleccionarPadre.sizePolicy().hasHeightForWidth())
        self.comboBox_SeleccionarPadre.setSizePolicy(sizePolicy)
        self.comboBox_SeleccionarPadre.setEditable(True)
        self.comboBox_SeleccionarPadre.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.comboBox_SeleccionarPadre.setObjectName("comboBox_SeleccionarPadre")
        self.horizontalLayout_14.addWidget(self.comboBox_SeleccionarPadre)
        self.verticalLayout_18.addWidget(self.frame_SeleccionPadre)
        self.frame_DatosFiscalesPadreFactura = QtWidgets.QFrame(parent=self.frame_SeleccionarPadre)
        self.frame_DatosFiscalesPadreFactura.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DatosFiscalesPadreFactura.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DatosFiscalesPadreFactura.setObjectName("frame_DatosFiscalesPadreFactura")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_DatosFiscalesPadreFactura)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_RFCReceptor = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura)
        self.label_RFCReceptor.setObjectName("label_RFCReceptor")
        self.horizontalLayout_19.addWidget(self.label_RFCReceptor)
        self.lineEdit_RFCReceptor = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura)
        self.lineEdit_RFCReceptor.setReadOnly(True)
        self.lineEdit_RFCReceptor.setObjectName("lineEdit_RFCReceptor")
        self.horizontalLayout_19.addWidget(self.lineEdit_RFCReceptor)
        self.label_NombreReceptor = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura)
        self.label_NombreReceptor.setObjectName("label_NombreReceptor")
        self.horizontalLayout_19.addWidget(self.label_NombreReceptor)
        self.lineEdit_NombreReceptor = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura)
        self.lineEdit_NombreReceptor.setReadOnly(True)
        self.lineEdit_NombreReceptor.setObjectName("lineEdit_NombreReceptor")
        self.horizontalLayout_19.addWidget(self.lineEdit_NombreReceptor)
        self.label_ApellidosReceptor = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura)
        self.label_ApellidosReceptor.setObjectName("label_ApellidosReceptor")
        self.horizontalLayout_19.addWidget(self.label_ApellidosReceptor)
        self.lineEdit_ApellidosReceptor = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura)
        self.lineEdit_ApellidosReceptor.setReadOnly(True)
        self.lineEdit_ApellidosReceptor.setObjectName("lineEdit_ApellidosReceptor")
        self.horizontalLayout_19.addWidget(self.lineEdit_ApellidosReceptor)
        self.label__DomicilioFiscal = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura)
        self.label__DomicilioFiscal.setObjectName("label__DomicilioFiscal")
        self.horizontalLayout_19.addWidget(self.label__DomicilioFiscal)
        self.lineEdit_DomicilioFiscal = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura)
        self.lineEdit_DomicilioFiscal.setReadOnly(True)
        self.lineEdit_DomicilioFiscal.setObjectName("lineEdit_DomicilioFiscal")
        self.horizontalLayout_19.addWidget(self.lineEdit_DomicilioFiscal)
        self.label_RegimenFiscal = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura)
        self.label_RegimenFiscal.setObjectName("label_RegimenFiscal")
        self.horizontalLayout_19.addWidget(self.label_RegimenFiscal)
        self.lineEdit_RegimenFiscal = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura)
        self.lineEdit_RegimenFiscal.setReadOnly(True)
        self.lineEdit_RegimenFiscal.setObjectName("lineEdit_RegimenFiscal")
        self.horizontalLayout_19.addWidget(self.lineEdit_RegimenFiscal)
        self.verticalLayout_18.addWidget(self.frame_DatosFiscalesPadreFactura)
        self.frame_DatosFiscalesPadreFactura_2 = QtWidgets.QFrame(parent=self.frame_SeleccionarPadre)
        self.frame_DatosFiscalesPadreFactura_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DatosFiscalesPadreFactura_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DatosFiscalesPadreFactura_2.setObjectName("frame_DatosFiscalesPadreFactura_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_DatosFiscalesPadreFactura_2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_UsoCFDI = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.label_UsoCFDI.setObjectName("label_UsoCFDI")
        self.horizontalLayout_20.addWidget(self.label_UsoCFDI)
        self.comboBox_UsoCFDI = QtWidgets.QComboBox(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.comboBox_UsoCFDI.setObjectName("comboBox_UsoCFDI")
        self.horizontalLayout_20.addWidget(self.comboBox_UsoCFDI)
        self.label_Moneda = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.label_Moneda.setObjectName("label_Moneda")
        self.horizontalLayout_20.addWidget(self.label_Moneda)
        self.lineEdit_Moneda = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.lineEdit_Moneda.setObjectName("lineEdit_Moneda")
        self.horizontalLayout_20.addWidget(self.lineEdit_Moneda)
        self.label_FormaPago = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.label_FormaPago.setObjectName("label_FormaPago")
        self.horizontalLayout_20.addWidget(self.label_FormaPago)
        self.lineEdit_FormaPago = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.lineEdit_FormaPago.setObjectName("lineEdit_FormaPago")
        self.horizontalLayout_20.addWidget(self.lineEdit_FormaPago)
        self.label_MetodoPago = QtWidgets.QLabel(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.label_MetodoPago.setObjectName("label_MetodoPago")
        self.horizontalLayout_20.addWidget(self.label_MetodoPago)
        self.lineEdit_MetodoPago = QtWidgets.QLineEdit(parent=self.frame_DatosFiscalesPadreFactura_2)
        self.lineEdit_MetodoPago.setObjectName("lineEdit_MetodoPago")
        self.horizontalLayout_20.addWidget(self.lineEdit_MetodoPago)
        self.verticalLayout_18.addWidget(self.frame_DatosFiscalesPadreFactura_2)
        self.verticalLayout_17.addWidget(self.frame_SeleccionarPadre)
        self.frame_SeleccionarAlumno = QtWidgets.QFrame(parent=self.page_Factura)
        self.frame_SeleccionarAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SeleccionarAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SeleccionarAlumno.setObjectName("frame_SeleccionarAlumno")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_SeleccionarAlumno)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_SeleccionAlumno = QtWidgets.QFrame(parent=self.frame_SeleccionarAlumno)
        self.frame_SeleccionAlumno.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_SeleccionAlumno.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SeleccionAlumno.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SeleccionAlumno.setObjectName("frame_SeleccionAlumno")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_SeleccionAlumno)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_lupaSeleccionarAlumno = QtWidgets.QPushButton(parent=self.frame_SeleccionAlumno)
        self.pushButton_lupaSeleccionarAlumno.setText("")
        self.pushButton_lupaSeleccionarAlumno.setIcon(icon7)
        self.pushButton_lupaSeleccionarAlumno.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_lupaSeleccionarAlumno.setObjectName("pushButton_lupaSeleccionarAlumno")
        self.horizontalLayout_21.addWidget(self.pushButton_lupaSeleccionarAlumno)
        self.comboBox_SeleccionarAlumno = QtWidgets.QComboBox(parent=self.frame_SeleccionAlumno)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SeleccionarAlumno.sizePolicy().hasHeightForWidth())
        self.comboBox_SeleccionarAlumno.setSizePolicy(sizePolicy)
        self.comboBox_SeleccionarAlumno.setEditable(True)
        self.comboBox_SeleccionarAlumno.setObjectName("comboBox_SeleccionarAlumno")
        self.horizontalLayout_21.addWidget(self.comboBox_SeleccionarAlumno)
        self.verticalLayout_19.addWidget(self.frame_SeleccionAlumno)
        self.frame_DatosFactura = QtWidgets.QFrame(parent=self.frame_SeleccionarAlumno)
        self.frame_DatosFactura.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DatosFactura.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DatosFactura.setObjectName("frame_DatosFactura")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_DatosFactura)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_ObjetoImpuesto = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_ObjetoImpuesto.setObjectName("label_ObjetoImpuesto")
        self.horizontalLayout_22.addWidget(self.label_ObjetoImpuesto)
        self.comboBox_ObjetoImpuesto = QtWidgets.QComboBox(parent=self.frame_DatosFactura)
        self.comboBox_ObjetoImpuesto.setEditable(False)
        self.comboBox_ObjetoImpuesto.setObjectName("comboBox_ObjetoImpuesto")
        self.horizontalLayout_22.addWidget(self.comboBox_ObjetoImpuesto)
        self.label_ExcentoIVA = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_ExcentoIVA.setObjectName("label_ExcentoIVA")
        self.horizontalLayout_22.addWidget(self.label_ExcentoIVA)
        self.lineEdit_ExcentoIVA = QtWidgets.QLineEdit(parent=self.frame_DatosFactura)
        self.lineEdit_ExcentoIVA.setObjectName("lineEdit_ExcentoIVA")
        self.horizontalLayout_22.addWidget(self.lineEdit_ExcentoIVA)
        self.label_Cantidad = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_Cantidad.setObjectName("label_Cantidad")
        self.horizontalLayout_22.addWidget(self.label_Cantidad)
        self.lineEdit_Cantidad = QtWidgets.QLineEdit(parent=self.frame_DatosFactura)
        self.lineEdit_Cantidad.setObjectName("lineEdit_Cantidad")
        self.horizontalLayout_22.addWidget(self.lineEdit_Cantidad)
        self.label_Unidad = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_Unidad.setObjectName("label_Unidad")
        self.horizontalLayout_22.addWidget(self.label_Unidad)
        self.lineEdit_Unidad = QtWidgets.QLineEdit(parent=self.frame_DatosFactura)
        self.lineEdit_Unidad.setObjectName("lineEdit_Unidad")
        self.horizontalLayout_22.addWidget(self.lineEdit_Unidad)
        self.label_Descripcion = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_Descripcion.setObjectName("label_Descripcion")
        self.horizontalLayout_22.addWidget(self.label_Descripcion)
        self.lineEdit_Descripcion = QtWidgets.QLineEdit(parent=self.frame_DatosFactura)
        self.lineEdit_Descripcion.setObjectName("lineEdit_Descripcion")
        self.horizontalLayout_22.addWidget(self.lineEdit_Descripcion)
        self.label_Precio = QtWidgets.QLabel(parent=self.frame_DatosFactura)
        self.label_Precio.setObjectName("label_Precio")
        self.horizontalLayout_22.addWidget(self.label_Precio)
        self.lineEdit_Precio = QtWidgets.QLineEdit(parent=self.frame_DatosFactura)
        self.lineEdit_Precio.setObjectName("lineEdit_Precio")
        self.horizontalLayout_22.addWidget(self.lineEdit_Precio)
        self.verticalLayout_19.addWidget(self.frame_DatosFactura)
        self.frame_TablaDatosFactura = QtWidgets.QFrame(parent=self.frame_SeleccionarAlumno)
        self.frame_TablaDatosFactura.setStyleSheet("")
        self.frame_TablaDatosFactura.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TablaDatosFactura.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TablaDatosFactura.setObjectName("frame_TablaDatosFactura")
        self.horizontalLayout_TablaDatosFactura = QtWidgets.QHBoxLayout(self.frame_TablaDatosFactura)
        self.horizontalLayout_TablaDatosFactura.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_TablaDatosFactura.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_TablaDatosFactura.setSpacing(0)
        self.horizontalLayout_TablaDatosFactura.setObjectName("horizontalLayout_TablaDatosFactura")
        self.tableWidget_DatosFactura = QtWidgets.QTableWidget(parent=self.frame_TablaDatosFactura)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_DatosFactura.sizePolicy().hasHeightForWidth())
        self.tableWidget_DatosFactura.setSizePolicy(sizePolicy)
        self.tableWidget_DatosFactura.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        self.tableWidget_DatosFactura.setFont(font)
        self.tableWidget_DatosFactura.setStyleSheet("QTableWidget{\n"
"background-color:rgb(217,217,217);\n"
"color: black;\n"
"font-size: 16px;\n"
"font-family:arial;\n"
"Padding:3px;\n"
"}\n"
"QHeaderView::section{ \n"
"color: black; \n"
"font-weight: bold; \n"
"}")
        self.tableWidget_DatosFactura.setObjectName("tableWidget_DatosFactura")
        self.tableWidget_DatosFactura.setColumnCount(9)
        self.tableWidget_DatosFactura.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DatosFactura.setHorizontalHeaderItem(8, item)
        self.horizontalLayout_TablaDatosFactura.addWidget(self.tableWidget_DatosFactura)
        self.verticalLayout_19.addWidget(self.frame_TablaDatosFactura)
        self.frame_BotonesFactura = QtWidgets.QFrame(parent=self.frame_SeleccionarAlumno)
        self.frame_BotonesFactura.setStyleSheet("QPushButton{\n"
"background-color:rgb(217,217,217);\n"
"font-size:16px;\n"
"font-family:Arial;\n"
"padding:6;\n"
"}")
        self.frame_BotonesFactura.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_BotonesFactura.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_BotonesFactura.setObjectName("frame_BotonesFactura")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_BotonesFactura)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(10)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_EliminarFactura = QtWidgets.QPushButton(parent=self.frame_BotonesFactura)
        self.pushButton_EliminarFactura.setStyleSheet("QPushButton{\n"
"background-color:rgb(209,48,48);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(210,50,50);\n"
"border:1px solid black;\n"
"}")
        self.pushButton_EliminarFactura.setObjectName("pushButton_EliminarFactura")
        self.horizontalLayout_23.addWidget(self.pushButton_EliminarFactura)
        self.pushButton_VisualizarFactura = QtWidgets.QPushButton(parent=self.frame_BotonesFactura)
        self.pushButton_VisualizarFactura.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(220,220,220);\n"
"border:1px solid black;\n"
"}")
        self.pushButton_VisualizarFactura.setIcon(icon8)
        self.pushButton_VisualizarFactura.setObjectName("pushButton_VisualizarFactura")
        self.horizontalLayout_23.addWidget(self.pushButton_VisualizarFactura)
        self.pushButton_CrearFactura = QtWidgets.QPushButton(parent=self.frame_BotonesFactura)
        self.pushButton_CrearFactura.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(220,220,220);\n"
"border:1px solid black;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icono_Proyecto/Icono_enviar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_CrearFactura.setIcon(icon9)
        self.pushButton_CrearFactura.setObjectName("pushButton_CrearFactura")
        self.horizontalLayout_23.addWidget(self.pushButton_CrearFactura)
        self.verticalLayout_19.addWidget(self.frame_BotonesFactura, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_17.addWidget(self.frame_SeleccionarAlumno)
        self.stackedWidget.addWidget(self.page_Factura)
        self.page_Padre = QtWidgets.QWidget()
        self.page_Padre.setStyleSheet("QLineEdit{\n"
"border-radius:5px;\n"
"background-color: rgb(217,217,217);\n"
"padding: 7px;\n"
"color: rgb(0,0,0);\n"
"font-size: 16px;\n"
"font-family:Arial;\n"
"}\n"
"\n"
"QLabel{\n"
"color:rgb(0,0,0);\n"
"font-family:Arial;\n"
"font-size:16px;\n"
"}")
        self.page_Padre.setObjectName("page_Padre")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_Padre)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_SuperiorPadre = QtWidgets.QFrame(parent=self.page_Padre)
        self.frame_SuperiorPadre.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_SuperiorPadre.setStyleSheet("QComboBox{\n"
"background-color: rgb(217,217,217);\n"
"color:black;\n"
"padding: 5px;\n"
"font-size:16px;\n"
"font-family:arial;\n"
"border-radius: 10px;\n"
"}")
        self.frame_SuperiorPadre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_SuperiorPadre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_SuperiorPadre.setObjectName("frame_SuperiorPadre")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_SuperiorPadre)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_lupaBuscarPadre = QtWidgets.QPushButton(parent=self.frame_SuperiorPadre)
        self.pushButton_lupaBuscarPadre.setText("")
        self.pushButton_lupaBuscarPadre.setIcon(icon7)
        self.pushButton_lupaBuscarPadre.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_lupaBuscarPadre.setObjectName("pushButton_lupaBuscarPadre")
        self.horizontalLayout_10.addWidget(self.pushButton_lupaBuscarPadre)
        self.comboBox_BuscarPadre = QtWidgets.QComboBox(parent=self.frame_SuperiorPadre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_BuscarPadre.sizePolicy().hasHeightForWidth())
        self.comboBox_BuscarPadre.setSizePolicy(sizePolicy)
        self.comboBox_BuscarPadre.setEditable(True)
        self.comboBox_BuscarPadre.setObjectName("comboBox_BuscarPadre")
        self.horizontalLayout_10.addWidget(self.comboBox_BuscarPadre)
        self.verticalLayout_12.addWidget(self.frame_SuperiorPadre)
        self.frame_Principal_Padre = QtWidgets.QFrame(parent=self.page_Padre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Principal_Padre.sizePolicy().hasHeightForWidth())
        self.frame_Principal_Padre.setSizePolicy(sizePolicy)
        self.frame_Principal_Padre.setMaximumSize(QtCore.QSize(1000, 200))
        self.frame_Principal_Padre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Principal_Padre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Principal_Padre.setObjectName("frame_Principal_Padre")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_Principal_Padre)
        self.formLayout_3.setContentsMargins(-1, -1, 10, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.frame_LabelPadre = QtWidgets.QFrame(parent=self.frame_Principal_Padre)
        self.frame_LabelPadre.setStyleSheet("padding:0px;")
        self.frame_LabelPadre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_LabelPadre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_LabelPadre.setObjectName("frame_LabelPadre")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_LabelPadre)
        self.verticalLayout_13.setContentsMargins(25, 0, 10, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_NombreAlumno_2 = QtWidgets.QLabel(parent=self.frame_LabelPadre)
        self.label_NombreAlumno_2.setObjectName("label_NombreAlumno_2")
        self.verticalLayout_13.addWidget(self.label_NombreAlumno_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_LabelPadre)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_13.addWidget(self.label_3)
        self.label_ApellidosAlumno_2 = QtWidgets.QLabel(parent=self.frame_LabelPadre)
        self.label_ApellidosAlumno_2.setObjectName("label_ApellidosAlumno_2")
        self.verticalLayout_13.addWidget(self.label_ApellidosAlumno_2)
        self.label_CurpAlumno_2 = QtWidgets.QLabel(parent=self.frame_LabelPadre)
        self.label_CurpAlumno_2.setObjectName("label_CurpAlumno_2")
        self.verticalLayout_13.addWidget(self.label_CurpAlumno_2)
        self.label_ClaveTrabajoAlumno_2 = QtWidgets.QLabel(parent=self.frame_LabelPadre)
        self.label_ClaveTrabajoAlumno_2.setObjectName("label_ClaveTrabajoAlumno_2")
        self.verticalLayout_13.addWidget(self.label_ClaveTrabajoAlumno_2)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.frame_LabelPadre)
        self.frame_LineEditPadre = QtWidgets.QFrame(parent=self.frame_Principal_Padre)
        self.frame_LineEditPadre.setMaximumSize(QtCore.QSize(900, 200))
        self.frame_LineEditPadre.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_LineEditPadre.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_LineEditPadre.setObjectName("frame_LineEditPadre")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_LineEditPadre)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_NombrePadre = QtWidgets.QLineEdit(parent=self.frame_LineEditPadre)
        self.lineEdit_NombrePadre.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_NombrePadre.setMaxLength(50)
        self.lineEdit_NombrePadre.setObjectName("lineEdit_NombrePadre")
        self.verticalLayout_14.addWidget(self.lineEdit_NombrePadre)
        self.lineEdit_ApellidoPpadre = QtWidgets.QLineEdit(parent=self.frame_LineEditPadre)
        self.lineEdit_ApellidoPpadre.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEdit_ApellidoPpadre.setObjectName("lineEdit_ApellidoPpadre")
        self.verticalLayout_14.addWidget(self.lineEdit_ApellidoPpadre)
        self.lineEdit_ApellidoMpadre = QtWidgets.QLineEdit(parent=self.frame_LineEditPadre)
        self.lineEdit_ApellidoMpadre.setMaxLength(50)
        self.lineEdit_ApellidoMpadre.setObjectName("lineEdit_ApellidoMpadre")
        self.verticalLayout_14.addWidget(self.lineEdit_ApellidoMpadre)
        self.lineEdit_RFCPadre = QtWidgets.QLineEdit(parent=self.frame_LineEditPadre)
        self.lineEdit_RFCPadre.setObjectName("lineEdit_RFCPadre")
        self.verticalLayout_14.addWidget(self.lineEdit_RFCPadre)
        self.lineEdit_CorreoElectronicoPadre = QtWidgets.QLineEdit(parent=self.frame_LineEditPadre)
        self.lineEdit_CorreoElectronicoPadre.setObjectName("lineEdit_CorreoElectronicoPadre")
        self.verticalLayout_14.addWidget(self.lineEdit_CorreoElectronicoPadre)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_LineEditPadre)
        self.verticalLayout_12.addWidget(self.frame_Principal_Padre)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label = QtWidgets.QLabel(parent=self.page_Padre)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("QLabel{\n"
"font-size: 15px;\n"
"font-family: arial;\n"
"color:black;\n"
"Font-weight:bold;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.verticalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(25, -1, 10, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_17.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.comboBox_Regimen = QtWidgets.QComboBox(parent=self.page_Padre)
        self.comboBox_Regimen.setMaximumSize(QtCore.QSize(900, 35))
        self.comboBox_Regimen.setStyleSheet("QComboBox{\n"
"padding: 5px;\n"
"border-radius:5px;\n"
"background-color:rgb(217,217,217);\n"
"color:black;\n"
"font-size:16px;\n"
"font-family:arial;\n"
"}")
        self.comboBox_Regimen.setObjectName("comboBox_Regimen")
        self.horizontalLayout_7.addWidget(self.comboBox_Regimen)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(20, -1, 0, -1)
        self.formLayout_4.setHorizontalSpacing(20)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lineEdit_Calle = QtWidgets.QLineEdit(parent=self.page_Padre)
        self.lineEdit_Calle.setObjectName("lineEdit_Calle")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Calle)
        self.lineEdit_CodigoPostal = QtWidgets.QLineEdit(parent=self.page_Padre)
        self.lineEdit_CodigoPostal.setMinimumSize(QtCore.QSize(340, 0))
        self.lineEdit_CodigoPostal.setObjectName("lineEdit_CodigoPostal")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_CodigoPostal)
        self.label_18 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_19)
        self.horizontalLayout_12.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setHorizontalSpacing(20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_21 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_21)
        self.lineEdit_Colonia = QtWidgets.QLineEdit(parent=self.page_Padre)
        self.lineEdit_Colonia.setObjectName("lineEdit_Colonia")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Colonia)
        self.label_22 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_22)
        self.lineEdit_Estado = QtWidgets.QLineEdit(parent=self.page_Padre)
        self.lineEdit_Estado.setObjectName("lineEdit_Estado")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Estado)
        self.horizontalLayout_12.addLayout(self.formLayout_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(25, -1, 10, -1)
        self.horizontalLayout_11.setSpacing(50)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(parent=self.page_Padre)
        self.label_20.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.lineEdit_Municipio = QtWidgets.QLineEdit(parent=self.page_Padre)
        self.lineEdit_Municipio.setObjectName("lineEdit_Municipio")
        self.horizontalLayout_11.addWidget(self.lineEdit_Municipio)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.frame_18 = QtWidgets.QFrame(parent=self.page_Padre)
        self.frame_18.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background-color: rgb(206,202,210);\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_38.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_38.setSpacing(6)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.PushBoton_Insertar_Padre = QtWidgets.QPushButton(parent=self.frame_18)
        self.PushBoton_Insertar_Padre.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(80,150,210);\n"
"}")
        self.PushBoton_Insertar_Padre.setObjectName("PushBoton_Insertar_Padre")
        self.horizontalLayout_38.addWidget(self.PushBoton_Insertar_Padre)
        self.PushBoton_Modificar_Padre = QtWidgets.QPushButton(parent=self.frame_18)
        self.PushBoton_Modificar_Padre.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.PushBoton_Modificar_Padre.setObjectName("PushBoton_Modificar_Padre")
        self.horizontalLayout_38.addWidget(self.PushBoton_Modificar_Padre)
        self.PushBoton_Eliminar_Padre = QtWidgets.QPushButton(parent=self.frame_18)
        self.PushBoton_Eliminar_Padre.setEnabled(True)
        self.PushBoton_Eliminar_Padre.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(210,50,50);\n"
"color:White;\n"
"}")
        self.PushBoton_Eliminar_Padre.setObjectName("PushBoton_Eliminar_Padre")
        self.horizontalLayout_38.addWidget(self.PushBoton_Eliminar_Padre)
        self.verticalLayout_12.addWidget(self.frame_18)
        self.stackedWidget.addWidget(self.page_Padre)
        self.page_ModificarUsuario = QtWidgets.QWidget()
        self.page_ModificarUsuario.setObjectName("page_ModificarUsuario")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_ModificarUsuario)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.widget = QtWidgets.QWidget(parent=self.page_ModificarUsuario)
        self.widget.setObjectName("widget")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_14 = QtWidgets.QFrame(parent=self.widget)
        self.frame_14.setMaximumSize(QtCore.QSize(900, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        self.frame_15.setFont(font)
        self.frame_15.setStyleSheet("QLabel{\n"
"color:black;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_24.setSpacing(15)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_24.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_24.addWidget(self.label_7)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_24.addWidget(self.label_14)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_24.addWidget(self.label_8)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_24.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_24.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_24.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_24.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_24.addWidget(self.label_10)
        self.horizontalLayout_34.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_16.setStyleSheet("QLineEdit{\n"
"color:black;\n"
"background-color: rgb(206,210,202);\n"
"padding: 5px;\n"
"border-radius:5px;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_25.setSpacing(15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.comboBoxAlta = QtWidgets.QComboBox(parent=self.frame_16)
        self.comboBoxAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBoxAlta.setObjectName("comboBoxAlta")
        self.verticalLayout_25.addWidget(self.comboBoxAlta)
        self.RFCAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.RFCAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RFCAlta.setFont(font)
        self.RFCAlta.setObjectName("RFCAlta")
        self.verticalLayout_25.addWidget(self.RFCAlta)
        self.nombreAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.nombreAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.nombreAlta.setFont(font)
        self.nombreAlta.setObjectName("nombreAlta")
        self.verticalLayout_25.addWidget(self.nombreAlta)
        self.apellidoPAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.apellidoPAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.apellidoPAlta.setFont(font)
        self.apellidoPAlta.setObjectName("apellidoPAlta")
        self.verticalLayout_25.addWidget(self.apellidoPAlta)
        self.apellidoMAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.apellidoMAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.apellidoMAlta.setFont(font)
        self.apellidoMAlta.setObjectName("apellidoMAlta")
        self.verticalLayout_25.addWidget(self.apellidoMAlta)
        self.serialAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.serialAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.serialAlta.setFont(font)
        self.serialAlta.setObjectName("serialAlta")
        self.verticalLayout_25.addWidget(self.serialAlta)
        self.usuarioAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.usuarioAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.usuarioAlta.setFont(font)
        self.usuarioAlta.setObjectName("usuarioAlta")
        self.verticalLayout_25.addWidget(self.usuarioAlta)
        self.contraseAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.contraseAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.contraseAlta.setFont(font)
        self.contraseAlta.setObjectName("contraseAlta")
        self.verticalLayout_25.addWidget(self.contraseAlta)
        self.cargoAlta = QtWidgets.QLineEdit(parent=self.frame_16)
        self.cargoAlta.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cargoAlta.setFont(font)
        self.cargoAlta.setObjectName("cargoAlta")
        self.verticalLayout_25.addWidget(self.cargoAlta)
        self.horizontalLayout_34.addWidget(self.frame_16)
        self.horizontalLayout_34.setStretch(0, 20)
        self.horizontalLayout_34.setStretch(1, 80)
        self.verticalLayout_23.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(parent=self.widget)
        self.frame_13.setStyleSheet("QPushButton{\n"
"color:black;\n"
"background-color: rgb(206,202,210);\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.BotonInsertarAlta = QtWidgets.QPushButton(parent=self.frame_13)
        self.BotonInsertarAlta.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(80,150,210);\n"
"}")
        self.BotonInsertarAlta.setObjectName("BotonInsertarAlta")
        self.horizontalLayout_35.addWidget(self.BotonInsertarAlta)
        self.BotonModificarAlta = QtWidgets.QPushButton(parent=self.frame_13)
        self.BotonModificarAlta.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"}")
        self.BotonModificarAlta.setObjectName("BotonModificarAlta")
        self.horizontalLayout_35.addWidget(self.BotonModificarAlta)
        self.BotonEliminarAlta = QtWidgets.QPushButton(parent=self.frame_13)
        self.BotonEliminarAlta.setEnabled(True)
        self.BotonEliminarAlta.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: 1px solid black;\n"
"background-color:rgb(210,50,50);\n"
"color:White;\n"
"}")
        self.BotonEliminarAlta.setObjectName("BotonEliminarAlta")
        self.horizontalLayout_35.addWidget(self.BotonEliminarAlta)
        self.verticalLayout_23.addWidget(self.frame_13)
        self.verticalLayout_23.setStretch(0, 40)
        self.verticalLayout_23.setStretch(1, 20)
        self.verticalLayout_22.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_ModificarUsuario)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_6.addWidget(self.frame_Principal)
        self.horizontalLayout.addWidget(self.contenedorPrincipal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nombreAplicacion.setText(_translate("MainWindow", "FACTURTEC"))
        self.LabelUsuario.setText(_translate("MainWindow", "Nombre"))
        self.LabelCargo.setText(_translate("MainWindow", "Cargo"))
        self.pushButton_Alumno.setText(_translate("MainWindow", "Alumno"))
        self.pushButton_Padre.setText(_translate("MainWindow", "Padre de Familia"))
        self.pushButton_NuevaFactura.setText(_translate("MainWindow", "Nueva Factura"))
        self.pushButton_Informes.setText(_translate("MainWindow", "Informes"))
        self.pushButton_Bitacora.setText(_translate("MainWindow", "Bitacora"))
        self.pushButton_Respaldo.setText(_translate("MainWindow", "Modificar Usuarios"))
        self.pushButton_Cerrarsesion.setText(_translate("MainWindow", "Cerrar sesión"))
        self.label_Bienvenida.setText(_translate("MainWindow", "BIENVENIDO A FACTURTEC"))
        self.comboBox_BuscarAlumno.setCurrentText(_translate("MainWindow", "Buscar Alumno"))
        self.comboBox_BuscarAlumno.setPlaceholderText(_translate("MainWindow", "Buscar alumno"))
        self.label_NombreAlumno.setText(_translate("MainWindow", "Nombre del Alumno:"))
        self.label_2.setText(_translate("MainWindow", "Apellido Materno:"))
        self.label_ApellidosAlumno.setText(_translate("MainWindow", "Apellido Paterno:"))
        self.label_5.setText(_translate("MainWindow", "Fecha de Nacimiento"))
        self.label_CurpAlumno.setText(_translate("MainWindow", "CURP:"))
        self.label_ClaveTrabajoAlumno.setText(_translate("MainWindow", "Clave de trabajo:"))
        self.label_NivelEducativoAlumno.setText(_translate("MainWindow", "Nivel educativo:"))
        self.label_15.setText(_translate("MainWindow", "Cantidad a Pagar"))
        self.label_RFCtutorAlumno.setText(_translate("MainWindow", "RFC del tutor:"))
        self.lineEdit_Fecha_Nacimiento.setText(_translate("MainWindow", "DD/MM/AAAA"))
        self.label_CantidadPago.setText(_translate("MainWindow", "$ 0000"))
        self.PushBoton_Insertar_Alumno.setText(_translate("MainWindow", "INSERTAR"))
        self.PushBoton_Modificar_Alumno.setText(_translate("MainWindow", "MODIFICAR"))
        self.PushBoton_Eliminar_Alumno.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_4.setText(_translate("MainWindow", "HISTORIAL DE INGRESO A LA APLICACIÓN"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cargo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fecha entrada"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fecha salida"))
        self.pushButton_2.setText(_translate("MainWindow", "Visualizar"))
        self.comboBox_SeleccionarPadre.setCurrentText(_translate("MainWindow", "Seleccionar Padre"))
        self.comboBox_SeleccionarPadre.setPlaceholderText(_translate("MainWindow", "Buscar Padre"))
        self.label_RFCReceptor.setText(_translate("MainWindow", "RFC Recepetor:"))
        self.label_NombreReceptor.setText(_translate("MainWindow", "Nombre:"))
        self.label_ApellidosReceptor.setText(_translate("MainWindow", "Apellidos:"))
        self.label__DomicilioFiscal.setText(_translate("MainWindow", "Domicilio Fiscal:"))
        self.label_RegimenFiscal.setText(_translate("MainWindow", "Régimen Fiscal:"))
        self.label_UsoCFDI.setText(_translate("MainWindow", "Uso del CFDI:"))
        self.label_Moneda.setText(_translate("MainWindow", "Moneda:"))
        self.label_FormaPago.setText(_translate("MainWindow", "Forma de Pago:"))
        self.label_MetodoPago.setText(_translate("MainWindow", "Método de Pago:"))
        self.comboBox_SeleccionarAlumno.setCurrentText(_translate("MainWindow", "Seleccionar Alumno"))
        self.comboBox_SeleccionarAlumno.setPlaceholderText(_translate("MainWindow", "Buscar Alumno"))
        self.label_ObjetoImpuesto.setText(_translate("MainWindow", "Objeto Impuesto:"))
        self.label_ExcentoIVA.setText(_translate("MainWindow", "Excento IVA:"))
        self.label_Cantidad.setText(_translate("MainWindow", "Cantidad:"))
        self.label_Unidad.setText(_translate("MainWindow", "Unidad:"))
        self.label_Descripcion.setText(_translate("MainWindow", "Descripción:"))
        self.label_Precio.setText(_translate("MainWindow", "Precio:"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Clave del producto y/o Servicio"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "No. identificicación"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Clave unidad"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Unidad"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor unitario"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Importe"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Objeto Impuesto"))
        item = self.tableWidget_DatosFactura.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Descripción"))
        self.pushButton_EliminarFactura.setText(_translate("MainWindow", "Eliminar"))
        self.pushButton_VisualizarFactura.setText(_translate("MainWindow", "Visualizar"))
        self.pushButton_CrearFactura.setText(_translate("MainWindow", "Facturar"))
        self.comboBox_BuscarPadre.setCurrentText(_translate("MainWindow", "Buscar Padre"))
        self.comboBox_BuscarPadre.setPlaceholderText(_translate("MainWindow", "Buscar Padre"))
        self.label_NombreAlumno_2.setText(_translate("MainWindow", "Nombre del Padre:"))
        self.label_3.setText(_translate("MainWindow", "Apellido Materno:"))
        self.label_ApellidosAlumno_2.setText(_translate("MainWindow", "Apellido Paterno:"))
        self.label_CurpAlumno_2.setText(_translate("MainWindow", "RFC:"))
        self.label_ClaveTrabajoAlumno_2.setText(_translate("MainWindow", "Correo Electronico:"))
        self.label.setText(_translate("MainWindow", "DATOS FISCALES"))
        self.label_17.setText(_translate("MainWindow", "Regimen Fiscal :"))
        self.label_18.setText(_translate("MainWindow", "Codigo Postal :"))
        self.label_19.setText(_translate("MainWindow", "No.Calle :"))
        self.label_21.setText(_translate("MainWindow", "Colonia :"))
        self.label_22.setText(_translate("MainWindow", "Estado :"))
        self.label_20.setText(_translate("MainWindow", "Municipio :"))
        self.PushBoton_Insertar_Padre.setText(_translate("MainWindow", "INSERTAR"))
        self.PushBoton_Modificar_Padre.setText(_translate("MainWindow", "MODIFICAR"))
        self.PushBoton_Eliminar_Padre.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_6.setText(_translate("MainWindow", "BUSCAR"))
        self.label_7.setText(_translate("MainWindow", "RFC"))
        self.label_14.setText(_translate("MainWindow", "Nombre"))
        self.label_8.setText(_translate("MainWindow", "Apellido Paterno"))
        self.label_13.setText(_translate("MainWindow", "Apellido Materno"))
        self.label_12.setText(_translate("MainWindow", "No.Serial"))
        self.label_9.setText(_translate("MainWindow", "Usuario"))
        self.label_11.setText(_translate("MainWindow", "Contraseña"))
        self.label_10.setText(_translate("MainWindow", "Cargo"))
        self.BotonInsertarAlta.setText(_translate("MainWindow", "INSERTAR"))
        self.BotonModificarAlta.setText(_translate("MainWindow", "MODIFICAR"))
        self.BotonEliminarAlta.setText(_translate("MainWindow", "ELIMINAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
