# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("QLabel{\n"
"font-size:32px;\n"
"fotn-family:arial;\n"
"color:black;\n"
"}\n"
"QLineEdit{\n"
"font-size:16px;\n"
"font-family:arial;\n"
"border-radius: 10px;\n"
"padding:5px;\n"
"background-color:rgb(206,202,210)\n"
"}\n"
"QPushButton{\n"
"font-size:16px;\n"
"font-family:arial;\n"
"border-radius: 10px;\n"
"padding:5px;\n"
"background-color:rgb(62,46,158);\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid white;\n"
"}\n"
"QLineEdit:hover{\n"
"border:1px solid black;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1px solid black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_NombreApp = QtWidgets.QLabel(parent=self.frame_2)
        self.label_NombreApp.setText("")
        self.label_NombreApp.setPixmap(QtGui.QPixmap("Icono_Proyecto/Facturitec_logo_transparent 1.png"))
        self.label_NombreApp.setScaledContents(True)
        self.label_NombreApp.setObjectName("label_NombreApp")
        self.verticalLayout_2.addWidget(self.label_NombreApp, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.userImput = QtWidgets.QLineEdit(parent=self.frame_2)
        self.userImput.setMinimumSize(QtCore.QSize(200, 0))
        self.userImput.setMaxLength(12)
        self.userImput.setObjectName("userImput")
        self.verticalLayout_2.addWidget(self.userImput, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.frame_2)
        self.passwordInput.setMinimumSize(QtCore.QSize(200, 0))
        self.passwordInput.setMaxLength(12)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout_2.addWidget(self.passwordInput, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.loginButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.loginButton.setMinimumSize(QtCore.QSize(150, 0))
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userImput.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.loginButton.setText(_translate("MainWindow", "Iniciar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
